// R glue for tbats.h: converts arguments and results, nothing else. The
// entry points are internal R functions generated by Rcpp attributes; the
// fable model methods in R/ call them.

#include <Rcpp.h>

#include <optional>
#include <sstream>
#include <string>
#include <vector>

#include "tbats/tbats.h"

namespace {

std::vector<double> numeric_or_empty(const Rcpp::List &list, const char *name) {
  if (!list.containsElementNamed(name)) return {};
  const SEXP value = list[name];
  if (Rf_isNull(value)) return {};
  return Rcpp::as<std::vector<double>>(value);
}

double scalar_or(const Rcpp::List &list, const char *name,
                 const double fallback) {
  if (!list.containsElementNamed(name)) return fallback;
  const SEXP value = list[name];
  if (Rf_isNull(value)) return fallback;
  return Rcpp::as<double>(value);
}

std::optional<bool> optional_flag(const Rcpp::List &list, const char *name) {
  if (!list.containsElementNamed(name)) return std::nullopt;
  const SEXP value = list[name];
  if (Rf_isNull(value)) return std::nullopt;
  return Rcpp::as<bool>(value);
}

tbats::ModelSpec spec_from(const Rcpp::List &list) {
  tbats::ModelSpec spec;
  spec.box_cox = Rcpp::as<bool>(list["box_cox"]);
  spec.box_cox_lower = scalar_or(list, "box_cox_lower", 0.0);
  spec.box_cox_upper = scalar_or(list, "box_cox_upper", 1.0);
  spec.trend = Rcpp::as<bool>(list["trend"]);
  spec.damping = Rcpp::as<bool>(list["damping"]);
  const std::string type = Rcpp::as<std::string>(list["seasonal_type"]);
  if (type == "dummy") {
    spec.seasonal_type = tbats::SeasonalType::kDummy;
  } else if (type == "trigonometric") {
    spec.seasonal_type = tbats::SeasonalType::kTrigonometric;
  } else {
    Rcpp::stop("seasonal_type must be 'dummy' or 'trigonometric'");
  }
  const std::vector<double> periods = numeric_or_empty(list, "periods");
  const std::vector<double> harmonics = numeric_or_empty(list, "harmonics");
  for (std::size_t i = 0; i < periods.size(); ++i) {
    const std::size_t k =
        i < harmonics.size() ? static_cast<std::size_t>(harmonics[i]) : 0;
    spec.seasonal.push_back({periods[i], k});
  }
  spec.p = static_cast<std::size_t>(scalar_or(list, "p", 0.0));
  spec.q = static_cast<std::size_t>(scalar_or(list, "q", 0.0));
  spec.validate();
  return spec;
}

Rcpp::List spec_to(const tbats::ModelSpec &spec) {
  std::vector<double> periods, harmonics;
  for (const auto &p : spec.seasonal) {
    periods.push_back(p.period);
    harmonics.push_back(static_cast<double>(p.harmonics));
  }
  return Rcpp::List::create(
      Rcpp::Named("box_cox") = spec.box_cox,
      Rcpp::Named("box_cox_lower") = spec.box_cox_lower,
      Rcpp::Named("box_cox_upper") = spec.box_cox_upper,
      Rcpp::Named("trend") = spec.trend, Rcpp::Named("damping") = spec.damping,
      Rcpp::Named("seasonal_type") =
          spec.seasonal_type == tbats::SeasonalType::kDummy ? "dummy"
                                                             : "trigonometric",
      Rcpp::Named("periods") = periods, Rcpp::Named("harmonics") = harmonics,
      Rcpp::Named("p") = static_cast<double>(spec.p),
      Rcpp::Named("q") = static_cast<double>(spec.q));
}

tbats::Parameters parameters_from(const Rcpp::List &list) {
  tbats::Parameters par;
  par.lambda = scalar_or(list, "lambda", 1.0);
  par.alpha = scalar_or(list, "alpha", 0.0);
  par.beta = scalar_or(list, "beta", 0.0);
  par.phi = scalar_or(list, "phi", 1.0);
  par.gamma_one = numeric_or_empty(list, "gamma_one");
  par.gamma_two = numeric_or_empty(list, "gamma_two");
  par.ar = numeric_or_empty(list, "ar");
  par.ma = numeric_or_empty(list, "ma");
  return par;
}

Rcpp::List parameters_to(const tbats::Parameters &par) {
  return Rcpp::List::create(
      Rcpp::Named("lambda") = par.lambda, Rcpp::Named("alpha") = par.alpha,
      Rcpp::Named("beta") = par.beta, Rcpp::Named("phi") = par.phi,
      Rcpp::Named("gamma_one") = par.gamma_one,
      Rcpp::Named("gamma_two") = par.gamma_two, Rcpp::Named("ar") = par.ar,
      Rcpp::Named("ma") = par.ma);
}

Rcpp::NumericMatrix matrix_to(const tbats::Matrix &m) {
  Rcpp::NumericMatrix out(static_cast<int>(m.rows()),
                          static_cast<int>(m.cols()));
  std::copy(m.storage().begin(), m.storage().end(), out.begin());
  return out;
}

tbats::Matrix matrix_from(const Rcpp::NumericMatrix &m) {
  tbats::Matrix out(static_cast<std::size_t>(m.nrow()),
                    static_cast<std::size_t>(m.ncol()));
  std::copy(m.begin(), m.end(), out.data());
  return out;
}

// The fitted model as the R side stores it.
Rcpp::List fitted_to(const tbats::FittedSpec &fit) {
  return Rcpp::List::create(
      Rcpp::Named("spec") = spec_to(fit.spec),
      Rcpp::Named("parameters") = parameters_to(fit.parameters),
      Rcpp::Named("n_parameters") =
          static_cast<double>(tbats::parameter_count(fit.spec)),
      Rcpp::Named("seed_states") = fit.seed_states,
      Rcpp::Named("errors") = fit.filter.errors,
      Rcpp::Named("predictions") = fit.filter.predictions,
      Rcpp::Named("fitted") = fit.fitted,
      Rcpp::Named("states") = matrix_to(fit.filter.states),
      Rcpp::Named("variance") = fit.variance,
      Rcpp::Named("neg2loglik") = fit.neg2loglik,
      Rcpp::Named("aic") = fit.aic,
      Rcpp::Named("evaluations") = static_cast<double>(fit.evaluations),
      Rcpp::Named("converged") = fit.converged);
}

tbats::FittedSpec fitted_from(const Rcpp::List &list) {
  const tbats::ModelSpec spec = spec_from(list["spec"]);
  const tbats::Parameters par = parameters_from(list["parameters"]);
  const std::vector<double> errors = Rcpp::as<std::vector<double>>(list["errors"]);
  const std::vector<double> predictions =
      Rcpp::as<std::vector<double>>(list["predictions"]);
  const tbats::Matrix states = matrix_from(Rcpp::NumericMatrix(list["states"]));
  tbats::FilterResult result(errors.size(), states.rows());
  result.errors = errors;
  result.predictions = predictions;
  result.states = states;
  std::vector<double> fitted = Rcpp::as<std::vector<double>>(list["fitted"]);
  const double neg2loglik = Rcpp::as<double>(list["neg2loglik"]);
  const tbats::OptimizationResult opt{
      neg2loglik, static_cast<std::size_t>(scalar_or(list, "evaluations", 0.0)),
      true};
  return tbats::FittedSpec(spec, par,
                           Rcpp::as<std::vector<double>>(list["seed_states"]),
                           std::move(result), std::move(fitted),
                           Rcpp::as<double>(list["variance"]), neg2loglik, opt);
}

tbats::OptimizerSettings optimizer_from(const Rcpp::List &opt) {
  tbats::OptimizerSettings o;
  if (opt.containsElementNamed("method")) {
    o.method = tbats::optimizer_from_name(Rcpp::as<std::string>(opt["method"]));
  }
  o.restarts = static_cast<std::size_t>(
      scalar_or(opt, "restarts", static_cast<double>(o.restarts)));
  o.simplex_fraction = scalar_or(opt, "simplex_fraction", o.simplex_fraction);
  o.tolerance = scalar_or(opt, "tolerance", o.tolerance);
  o.iterations_per_dim_squared = static_cast<std::size_t>(scalar_or(
      opt, "iterations_per_dim_squared",
      static_cast<double>(o.iterations_per_dim_squared)));
  o.max_iterations = static_cast<std::size_t>(
      scalar_or(opt, "max_iterations", static_cast<double>(o.max_iterations)));
  o.max_evaluations = static_cast<std::size_t>(scalar_or(
      opt, "max_evaluations", static_cast<double>(o.max_evaluations)));
  return o;
}

tbats::arma::ArmaSearch arma_search_from(const std::string &name) {
  if (name == "stepwise") return tbats::arma::ArmaSearch::kStepwise;
  if (name == "grid") return tbats::arma::ArmaSearch::kGrid;
  Rcpp::stop("arma_search must be 'stepwise' or 'grid'");
}

tbats::ForecastabilityCheck forecastability_from(const std::string &name) {
  if (name == "auto") return tbats::ForecastabilityCheck::kAuto;
  if (name == "on_improvement") return tbats::ForecastabilityCheck::kOnImprovement;
  if (name == "every_evaluation") return tbats::ForecastabilityCheck::kEveryEvaluation;
  Rcpp::stop("forecastability must be 'auto', 'on_improvement' or 'every_evaluation'");
}

tbats::SearchOptions search_options_from(const Rcpp::List &list) {
  tbats::SearchOptions o;
  o.box_cox = optional_flag(list, "box_cox");
  o.trend = optional_flag(list, "trend");
  o.damping = optional_flag(list, "damping");
  if (list.containsElementNamed("arma_errors") &&
      !Rf_isNull(list["arma_errors"])) {
    o.arma_errors = Rcpp::as<bool>(list["arma_errors"]);
  }
  o.box_cox_lower = scalar_or(list, "box_cox_lower", o.box_cox_lower);
  o.box_cox_upper = scalar_or(list, "box_cox_upper", o.box_cox_upper);
  if (list.containsElementNamed("bias_adjust") &&
      !Rf_isNull(list["bias_adjust"])) {
    o.bias_adjust = Rcpp::as<bool>(list["bias_adjust"]);
  }
  if (list.containsElementNamed("optimizer")) {
    o.optimizer = optimizer_from(list["optimizer"]);
  }
  if (list.containsElementNamed("arma_optimizer")) {
    const tbats::OptimizerSettings defaults = o.arma_optimizer;
    o.arma_optimizer = optimizer_from(list["arma_optimizer"]);
    if (!Rcpp::List(list["arma_optimizer"]).containsElementNamed("method")) {
      o.arma_optimizer.method = defaults.method;
    }
  }
  o.max_arma_order = static_cast<std::size_t>(
      scalar_or(list, "max_arma_order", static_cast<double>(o.max_arma_order)));
  if (list.containsElementNamed("arma_search")) {
    o.arma_search = arma_search_from(Rcpp::as<std::string>(list["arma_search"]));
  }
  if (list.containsElementNamed("forecastability")) {
    o.forecastability =
        forecastability_from(Rcpp::as<std::string>(list["forecastability"]));
  }
  return o;
}

std::vector<double> periods_from(const Rcpp::Nullable<Rcpp::NumericVector> &periods) {
  if (periods.isNull()) return {};
  return Rcpp::as<std::vector<double>>(periods.get());
}

}  // namespace

// ---- the model interface ----------------------------------------------------

// The full BATS ("bats") or TBATS ("tbats") search.
// [[Rcpp::export]]
Rcpp::List tbats_search(Rcpp::NumericVector y,
                        Rcpp::Nullable<Rcpp::NumericVector> periods,
                        std::string type, Rcpp::List options) {
  const std::vector<double> series = Rcpp::as<std::vector<double>>(y);
  const std::vector<double> seasonal = periods_from(periods);
  const tbats::SearchOptions o = search_options_from(options);
  if (type == "bats") return fitted_to(tbats::search_bats(series, seasonal, o));
  if (type == "tbats") return fitted_to(tbats::search_tbats(series, seasonal, o));
  Rcpp::stop("type must be 'bats' or 'tbats'");
}

// Forecast means and central interval bounds on the original scale, with
// the model-scale mean and variance.
// [[Rcpp::export]]
Rcpp::List tbats_forecast(Rcpp::List fit, int h, double level, bool bias_adjust) {
  const tbats::Forecast fc = tbats::forecast(fitted_from(fit),
                                             static_cast<std::size_t>(h),
                                             level, bias_adjust);
  return Rcpp::List::create(
      Rcpp::Named("mean") = fc.mean, Rcpp::Named("lower") = fc.lower,
      Rcpp::Named("upper") = fc.upper,
      Rcpp::Named("mean_model_scale") = fc.mean_model_scale,
      Rcpp::Named("variance_model_scale") = fc.variance_model_scale);
}

// Sample paths on the original scale, one column per path of the
// model-scale innovations.
// [[Rcpp::export]]
Rcpp::NumericMatrix tbats_simulate(Rcpp::List fit,
                                   Rcpp::NumericMatrix innovations) {
  return matrix_to(tbats::simulate(fitted_from(fit), matrix_from(innovations)));
}

// Level, slope and one seasonal effect per period, one row per observation.
// [[Rcpp::export]]
Rcpp::NumericMatrix tbats_components(Rcpp::List fit) {
  const tbats::FittedSpec model = fitted_from(fit);
  Rcpp::NumericMatrix out = matrix_to(tbats::components(model));
  Rcpp::CharacterVector names;
  names.push_back("level");
  if (model.spec.trend) names.push_back("slope");
  for (const auto &s : model.spec.seasonal) {
    std::ostringstream name;
    name << "season_" << s.period;
    names.push_back(name.str());
  }
  Rcpp::colnames(out) = names;
  return out;
}

// The same specification and parameters applied to another series.
// [[Rcpp::export]]
Rcpp::List tbats_refit(Rcpp::List fit, Rcpp::NumericVector y, bool bias_adjust) {
  return fitted_to(tbats::refit(fitted_from(fit),
                                Rcpp::as<std::vector<double>>(y), bias_adjust));
}

// ---- internal entry points used by the tests --------------------------------

// Dense w, F, g and the eigenvalue moduli of D: the kernel's content
// materialised for comparison.
// [[Rcpp::export]]
Rcpp::List tbats_dense_system(Rcpp::List spec, Rcpp::List par) {
  const tbats::System system(spec_from(spec), parameters_from(par));
  const tbats::Matrix D = system.D();
  const auto eigen = tinyqr::eigenvalues(D.data(), D.rows());
  std::vector<double> moduli(eigen.size());
  for (std::size_t i = 0; i < eigen.size(); ++i) moduli[i] = std::abs(eigen[i]);
  std::sort(moduli.begin(), moduli.end());
  return Rcpp::List::create(Rcpp::Named("w") = system.observation(),
                            Rcpp::Named("F") = matrix_to(system.transition()),
                            Rcpp::Named("g") = system.gain(),
                            Rcpp::Named("D_eigen_modulus") = moduli);
}

// [[Rcpp::export]]
std::vector<double> tbats_pack_parameters(Rcpp::List spec, Rcpp::List par) {
  return tbats::pack(spec_from(spec), parameters_from(par));
}

// [[Rcpp::export]]
Rcpp::List tbats_unpack_parameters(Rcpp::List spec, std::vector<double> vector) {
  return parameters_to(tbats::unpack(spec_from(spec), vector));
}

// [[Rcpp::export]]
std::vector<double> tbats_parameter_scales(Rcpp::List spec) {
  return tbats::parameter_scales(spec_from(spec));
}

// Filter the model-scale series y from the seed state x0.
// [[Rcpp::export]]
Rcpp::List tbats_filter(Rcpp::List spec, Rcpp::List par, std::vector<double> y,
                        std::vector<double> x0) {
  const tbats::System system(spec_from(spec), parameters_from(par));
  const tbats::FilterResult result = tbats::filter(system, y, x0);
  return Rcpp::List::create(Rcpp::Named("errors") = result.errors,
                            Rcpp::Named("predictions") = result.predictions,
                            Rcpp::Named("states") = matrix_to(result.states));
}

// [[Rcpp::export]]
Rcpp::List tbats_forecast_model_scale(Rcpp::List spec, Rcpp::List par,
                                      std::vector<double> x_last, double sigma2,
                                      int h) {
  const tbats::System system(spec_from(spec), parameters_from(par));
  const tbats::ForecastModelScale fc = tbats::forecast_model_scale(
      system, x_last, sigma2, static_cast<std::size_t>(h));
  return Rcpp::List::create(Rcpp::Named("mean") = fc.mean,
                            Rcpp::Named("variance") = fc.variance);
}

// [[Rcpp::export]]
Rcpp::NumericMatrix tbats_simulate_model_scale(Rcpp::List spec, Rcpp::List par,
                                               std::vector<double> x_last,
                                               Rcpp::NumericMatrix innovations) {
  const tbats::System system(spec_from(spec), parameters_from(par));
  return matrix_to(
      tbats::simulate_model_scale(system, x_last, matrix_from(innovations)));
}

// [[Rcpp::export]]
std::vector<double> tbats_box_cox(std::vector<double> y, double lambda) {
  return tbats::box_cox::transform(y, lambda);
}

// Inverse Box-Cox; with a non-null variance the bias-adjusted mean.
// [[Rcpp::export]]
std::vector<double> tbats_inv_box_cox(std::vector<double> z, double lambda,
                                      Rcpp::Nullable<double> variance) {
  if (variance.isNull()) return tbats::box_cox::inverse(z, lambda);
  const double v = Rcpp::as<double>(variance.get());
  std::vector<double> out(z.size());
  for (std::size_t i = 0; i < z.size(); ++i) {
    out[i] = tbats::box_cox::inverse_bias_adjusted(z[i], lambda, v);
  }
  return out;
}

// [[Rcpp::export]]
double tbats_guerrero_lambda(std::vector<double> y, int period, double lower,
                             double upper) {
  return tbats::box_cox::guerrero_lambda(y, static_cast<std::size_t>(period),
                                         lower, upper);
}

// Seed states (model scale) for a specification, parameters and model-scale
// series.
// [[Rcpp::export]]
std::vector<double> tbats_seed_states(Rcpp::List spec, Rcpp::List par,
                                      std::vector<double> y) {
  const tbats::System system(spec_from(spec), parameters_from(par));
  return tbats::seed::seed_states(system, y);
}

// -2 log L, AIC and admissibility at fixed parameters; `y` is the original
// series and `seed` the seed state on the model scale.
// [[Rcpp::export]]
Rcpp::List tbats_neg2loglik(Rcpp::List spec_list, Rcpp::List par_list,
                            std::vector<double> y, std::vector<double> seed) {
  const tbats::ModelSpec spec = spec_from(spec_list);
  const tbats::Parameters par = parameters_from(par_list);
  if (spec.box_cox) {
    for (double &v : seed) v = tbats::box_cox::inverse(v, par.lambda);
  }
  tbats::Likelihood objective(spec, y, seed);
  const double value = objective.evaluate(par);
  const tbats::System system(spec, par);
  const bool admissible =
      tbats::admissibility::parameters_admissible(spec, par) &&
      tbats::admissibility::system_admissible(system);
  return Rcpp::List::create(
      Rcpp::Named("neg2loglik") = value,
      Rcpp::Named("aic") =
          value + 2.0 * static_cast<double>(tbats::parameter_count(spec) +
                                            seed.size()),
      Rcpp::Named("admissible") = admissible);
}

// [[Rcpp::export]]
Rcpp::List tbats_fit_specific(Rcpp::List spec, std::vector<double> y,
                              double init_lambda, Rcpp::List optimizer,
                              bool bias_adjust,
                              std::string forecastability = "auto") {
  tbats::FitSettings settings;
  settings.optimizer = optimizer_from(optimizer);
  settings.bias_adjust = bias_adjust;
  settings.forecastability = forecastability_from(forecastability);
  return fitted_to(tbats::fit_specific(y, spec_from(spec), init_lambda, settings));
}

// Exact log-likelihood of ARMA(p, q) with the given coefficients and mean.
// [[Rcpp::export]]
Rcpp::List tbats_arma_loglik(std::vector<double> y, std::vector<double> ar,
                             std::vector<double> ma, double mean) {
  std::vector<double> centred(y.size());
  for (std::size_t t = 0; t < y.size(); ++t) centred[t] = y[t] - mean;
  tbats::arma::KalmanArma filter(ar.size(), ma.size());
  filter.reset(ar.data(), ma.data());
  const auto result = filter.likelihood(centred.data(), y.size());
  const double n = static_cast<double>(y.size());
  return Rcpp::List::create(
      Rcpp::Named("loglik") =
          -(n * result.objective + 0.5 * n * (1.0 + tbats::arma::kLogTwoPi)),
      Rcpp::Named("sigma2") = result.sigma2,
      Rcpp::Named("used") = static_cast<double>(result.used));
}

// [[Rcpp::export]]
Rcpp::List tbats_arma_fit(std::vector<double> y, int p, int q,
                          Rcpp::List optimizer) {
  tbats::OptimizerSettings settings = tbats::arma::arma_optimizer_defaults();
  if (optimizer.size() > 0) settings = optimizer_from(optimizer);
  const tbats::arma::ArmaFit fit = tbats::arma::fit_arma(
      y, static_cast<std::size_t>(p), static_cast<std::size_t>(q), settings);
  return Rcpp::List::create(
      Rcpp::Named("ar") = fit.ar, Rcpp::Named("ma") = fit.ma,
      Rcpp::Named("mean") = fit.mean, Rcpp::Named("sigma2") = fit.sigma2,
      Rcpp::Named("loglik") = fit.loglik, Rcpp::Named("aic") = fit.aic,
      Rcpp::Named("evaluations") = static_cast<double>(fit.evaluations),
      Rcpp::Named("converged") = fit.converged);
}

// [[Rcpp::export]]
Rcpp::List tbats_arma_select(std::vector<double> y, int max_p, int max_q,
                             Rcpp::List optimizer,
                             std::string search = "grid") {
  tbats::OptimizerSettings settings = tbats::arma::arma_optimizer_defaults();
  if (optimizer.size() > 0) settings = optimizer_from(optimizer);
  const std::vector<tbats::arma::ArmaOrder> orders = tbats::arma::arma_orders(
      y, static_cast<std::size_t>(max_p), static_cast<std::size_t>(max_q),
      settings, arma_search_from(search));
  const tbats::arma::ArmaOrder order = tbats::arma::best_order(orders);
  return Rcpp::List::create(Rcpp::Named("p") = static_cast<double>(order.p),
                            Rcpp::Named("q") = static_cast<double>(order.q),
                            Rcpp::Named("aic") = order.aic,
                            Rcpp::Named("fits") = static_cast<double>(orders.size()));
}
