// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tbats_search
Rcpp::List tbats_search(Rcpp::NumericVector y, Rcpp::Nullable<Rcpp::NumericVector> periods, std::string type, Rcpp::List options);
RcppExport SEXP _fable_tbats_tbats_search(SEXP ySEXP, SEXP periodsSEXP, SEXP typeSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type periods(periodsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_search(y, periods, type, options));
    return rcpp_result_gen;
END_RCPP
}
// tbats_forecast
Rcpp::List tbats_forecast(Rcpp::List fit, int h, double level, bool bias_adjust);
RcppExport SEXP _fable_tbats_tbats_forecast(SEXP fitSEXP, SEXP hSEXP, SEXP levelSEXP, SEXP bias_adjustSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type level(levelSEXP);
    Rcpp::traits::input_parameter< bool >::type bias_adjust(bias_adjustSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_forecast(fit, h, level, bias_adjust));
    return rcpp_result_gen;
END_RCPP
}
// tbats_simulate
Rcpp::NumericMatrix tbats_simulate(Rcpp::List fit, Rcpp::NumericMatrix innovations);
RcppExport SEXP _fable_tbats_tbats_simulate(SEXP fitSEXP, SEXP innovationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type innovations(innovationsSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_simulate(fit, innovations));
    return rcpp_result_gen;
END_RCPP
}
// tbats_components
Rcpp::NumericMatrix tbats_components(Rcpp::List fit);
RcppExport SEXP _fable_tbats_tbats_components(SEXP fitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fit(fitSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_components(fit));
    return rcpp_result_gen;
END_RCPP
}
// tbats_refit
Rcpp::List tbats_refit(Rcpp::List fit, Rcpp::NumericVector y, bool bias_adjust);
RcppExport SEXP _fable_tbats_tbats_refit(SEXP fitSEXP, SEXP ySEXP, SEXP bias_adjustSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type bias_adjust(bias_adjustSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_refit(fit, y, bias_adjust));
    return rcpp_result_gen;
END_RCPP
}
// tbats_dense_system
Rcpp::List tbats_dense_system(Rcpp::List spec, Rcpp::List par);
RcppExport SEXP _fable_tbats_tbats_dense_system(SEXP specSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_dense_system(spec, par));
    return rcpp_result_gen;
END_RCPP
}
// tbats_pack_parameters
std::vector<double> tbats_pack_parameters(Rcpp::List spec, Rcpp::List par);
RcppExport SEXP _fable_tbats_tbats_pack_parameters(SEXP specSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_pack_parameters(spec, par));
    return rcpp_result_gen;
END_RCPP
}
// tbats_unpack_parameters
Rcpp::List tbats_unpack_parameters(Rcpp::List spec, std::vector<double> vector);
RcppExport SEXP _fable_tbats_tbats_unpack_parameters(SEXP specSEXP, SEXP vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type vector(vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_unpack_parameters(spec, vector));
    return rcpp_result_gen;
END_RCPP
}
// tbats_parameter_scales
std::vector<double> tbats_parameter_scales(Rcpp::List spec);
RcppExport SEXP _fable_tbats_tbats_parameter_scales(SEXP specSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_parameter_scales(spec));
    return rcpp_result_gen;
END_RCPP
}
// tbats_filter
Rcpp::List tbats_filter(Rcpp::List spec, Rcpp::List par, std::vector<double> y, std::vector<double> x0);
RcppExport SEXP _fable_tbats_tbats_filter(SEXP specSEXP, SEXP parSEXP, SEXP ySEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_filter(spec, par, y, x0));
    return rcpp_result_gen;
END_RCPP
}
// tbats_forecast_model_scale
Rcpp::List tbats_forecast_model_scale(Rcpp::List spec, Rcpp::List par, std::vector<double> x_last, double sigma2, int h);
RcppExport SEXP _fable_tbats_tbats_forecast_model_scale(SEXP specSEXP, SEXP parSEXP, SEXP x_lastSEXP, SEXP sigma2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type x_last(x_lastSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_forecast_model_scale(spec, par, x_last, sigma2, h));
    return rcpp_result_gen;
END_RCPP
}
// tbats_simulate_model_scale
Rcpp::NumericMatrix tbats_simulate_model_scale(Rcpp::List spec, Rcpp::List par, std::vector<double> x_last, Rcpp::NumericMatrix innovations);
RcppExport SEXP _fable_tbats_tbats_simulate_model_scale(SEXP specSEXP, SEXP parSEXP, SEXP x_lastSEXP, SEXP innovationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type x_last(x_lastSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type innovations(innovationsSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_simulate_model_scale(spec, par, x_last, innovations));
    return rcpp_result_gen;
END_RCPP
}
// tbats_box_cox
std::vector<double> tbats_box_cox(std::vector<double> y, double lambda);
RcppExport SEXP _fable_tbats_tbats_box_cox(SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_box_cox(y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// tbats_inv_box_cox
std::vector<double> tbats_inv_box_cox(std::vector<double> z, double lambda, Rcpp::Nullable<double> variance);
RcppExport SEXP _fable_tbats_tbats_inv_box_cox(SEXP zSEXP, SEXP lambdaSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_inv_box_cox(z, lambda, variance));
    return rcpp_result_gen;
END_RCPP
}
// tbats_guerrero_lambda
double tbats_guerrero_lambda(std::vector<double> y, int period, double lower, double upper);
RcppExport SEXP _fable_tbats_tbats_guerrero_lambda(SEXP ySEXP, SEXP periodSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type period(periodSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_guerrero_lambda(y, period, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// tbats_seed_states
std::vector<double> tbats_seed_states(Rcpp::List spec, Rcpp::List par, std::vector<double> y);
RcppExport SEXP _fable_tbats_tbats_seed_states(SEXP specSEXP, SEXP parSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_seed_states(spec, par, y));
    return rcpp_result_gen;
END_RCPP
}
// tbats_neg2loglik
Rcpp::List tbats_neg2loglik(Rcpp::List spec_list, Rcpp::List par_list, std::vector<double> y, std::vector<double> seed);
RcppExport SEXP _fable_tbats_tbats_neg2loglik(SEXP spec_listSEXP, SEXP par_listSEXP, SEXP ySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec_list(spec_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type par_list(par_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_neg2loglik(spec_list, par_list, y, seed));
    return rcpp_result_gen;
END_RCPP
}
// tbats_fit_specific
Rcpp::List tbats_fit_specific(Rcpp::List spec, std::vector<double> y, double init_lambda, Rcpp::List optimizer, bool bias_adjust, std::string forecastability);
RcppExport SEXP _fable_tbats_tbats_fit_specific(SEXP specSEXP, SEXP ySEXP, SEXP init_lambdaSEXP, SEXP optimizerSEXP, SEXP bias_adjustSEXP, SEXP forecastabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type init_lambda(init_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type optimizer(optimizerSEXP);
    Rcpp::traits::input_parameter< bool >::type bias_adjust(bias_adjustSEXP);
    Rcpp::traits::input_parameter< std::string >::type forecastability(forecastabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_fit_specific(spec, y, init_lambda, optimizer, bias_adjust, forecastability));
    return rcpp_result_gen;
END_RCPP
}
// tbats_arma_loglik
Rcpp::List tbats_arma_loglik(std::vector<double> y, std::vector<double> ar, std::vector<double> ma, double mean);
RcppExport SEXP _fable_tbats_tbats_arma_loglik(SEXP ySEXP, SEXP arSEXP, SEXP maSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type ar(arSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type ma(maSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_arma_loglik(y, ar, ma, mean));
    return rcpp_result_gen;
END_RCPP
}
// tbats_arma_fit
Rcpp::List tbats_arma_fit(std::vector<double> y, int p, int q, Rcpp::List optimizer);
RcppExport SEXP _fable_tbats_tbats_arma_fit(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP, SEXP optimizerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type optimizer(optimizerSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_arma_fit(y, p, q, optimizer));
    return rcpp_result_gen;
END_RCPP
}
// tbats_arma_select
Rcpp::List tbats_arma_select(std::vector<double> y, int max_p, int max_q, Rcpp::List optimizer, std::string search);
RcppExport SEXP _fable_tbats_tbats_arma_select(SEXP ySEXP, SEXP max_pSEXP, SEXP max_qSEXP, SEXP optimizerSEXP, SEXP searchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_p(max_pSEXP);
    Rcpp::traits::input_parameter< int >::type max_q(max_qSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type optimizer(optimizerSEXP);
    Rcpp::traits::input_parameter< std::string >::type search(searchSEXP);
    rcpp_result_gen = Rcpp::wrap(tbats_arma_select(y, max_p, max_q, optimizer, search));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fable_tbats_tbats_search", (DL_FUNC) &_fable_tbats_tbats_search, 4},
    {"_fable_tbats_tbats_forecast", (DL_FUNC) &_fable_tbats_tbats_forecast, 4},
    {"_fable_tbats_tbats_simulate", (DL_FUNC) &_fable_tbats_tbats_simulate, 2},
    {"_fable_tbats_tbats_components", (DL_FUNC) &_fable_tbats_tbats_components, 1},
    {"_fable_tbats_tbats_refit", (DL_FUNC) &_fable_tbats_tbats_refit, 3},
    {"_fable_tbats_tbats_dense_system", (DL_FUNC) &_fable_tbats_tbats_dense_system, 2},
    {"_fable_tbats_tbats_pack_parameters", (DL_FUNC) &_fable_tbats_tbats_pack_parameters, 2},
    {"_fable_tbats_tbats_unpack_parameters", (DL_FUNC) &_fable_tbats_tbats_unpack_parameters, 2},
    {"_fable_tbats_tbats_parameter_scales", (DL_FUNC) &_fable_tbats_tbats_parameter_scales, 1},
    {"_fable_tbats_tbats_filter", (DL_FUNC) &_fable_tbats_tbats_filter, 4},
    {"_fable_tbats_tbats_forecast_model_scale", (DL_FUNC) &_fable_tbats_tbats_forecast_model_scale, 5},
    {"_fable_tbats_tbats_simulate_model_scale", (DL_FUNC) &_fable_tbats_tbats_simulate_model_scale, 4},
    {"_fable_tbats_tbats_box_cox", (DL_FUNC) &_fable_tbats_tbats_box_cox, 2},
    {"_fable_tbats_tbats_inv_box_cox", (DL_FUNC) &_fable_tbats_tbats_inv_box_cox, 3},
    {"_fable_tbats_tbats_guerrero_lambda", (DL_FUNC) &_fable_tbats_tbats_guerrero_lambda, 4},
    {"_fable_tbats_tbats_seed_states", (DL_FUNC) &_fable_tbats_tbats_seed_states, 3},
    {"_fable_tbats_tbats_neg2loglik", (DL_FUNC) &_fable_tbats_tbats_neg2loglik, 4},
    {"_fable_tbats_tbats_fit_specific", (DL_FUNC) &_fable_tbats_tbats_fit_specific, 6},
    {"_fable_tbats_tbats_arma_loglik", (DL_FUNC) &_fable_tbats_tbats_arma_loglik, 4},
    {"_fable_tbats_tbats_arma_fit", (DL_FUNC) &_fable_tbats_tbats_arma_fit, 4},
    {"_fable_tbats_tbats_arma_select", (DL_FUNC) &_fable_tbats_tbats_arma_select, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fable_tbats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
