#' @importFrom stats qnorm
#' @importFrom distributional dist_normal
#' @importFrom tsibble measured_vars
#' @importFrom stats as.ts
#' @importFrom stats residuals
#' @importFrom stats fitted
#' @importFrom fabletools new_specials
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
#' @importFrom stats spec.ar
#' @importFrom stats aggregate
#' @importFrom stats ts
#' @importFrom stats end
#' @importFrom stats frequency
#' @importFrom stats lm
#' @importFrom stats na.contiguous
#' @importFrom stats optim
#' @importFrom stats optimize
#' @importFrom stats sd
#' @importFrom stats start
#' @importFrom stats time
#' @importFrom stats tsp
#' @importFrom stats `tsp<-`
#' @importFrom parallel detectCores
#' @importFrom parallel makeCluster
#' @importFrom parallel clusterApplyLB
#' @importFrom parallel stopCluster
NULL
