#' @importFrom forecast forecast
#' @importFrom stats qnorm
#' @importFrom distributional dist_normal
#' @importFrom forecast tbats
#' @importFrom stats as.ts
#' @importFrom stats residuals
#' @importFrom stats fitted
#' @importFrom tsibble measured_vars
#' @importFrom forecast tbats.components
#' @importFrom tsibble as_tsibble
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr select
#' @importFrom tidyselect matches
#' @importFrom purrr map_dfc
#' @importFrom fabletools inv_box_cox
#' @importFrom dplyr bind_cols
#' @importFrom dplyr relocate
#' @importFrom tidyselect everything
#' @importFrom dplyr rename_with
#' @importFrom fabletools as_dable
#' @importFrom fabletools new_specials
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
NULL
