# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tbats_search <- function(y, periods, type, options) {
    .Call(`_fable_tbats_tbats_search`, y, periods, type, options)
}

tbats_forecast <- function(fit, h, level, bias_adjust) {
    .Call(`_fable_tbats_tbats_forecast`, fit, h, level, bias_adjust)
}

tbats_simulate <- function(fit, innovations) {
    .Call(`_fable_tbats_tbats_simulate`, fit, innovations)
}

tbats_components <- function(fit) {
    .Call(`_fable_tbats_tbats_components`, fit)
}

tbats_refit <- function(fit, y, bias_adjust) {
    .Call(`_fable_tbats_tbats_refit`, fit, y, bias_adjust)
}

tbats_dense_system <- function(spec, par) {
    .Call(`_fable_tbats_tbats_dense_system`, spec, par)
}

tbats_pack_parameters <- function(spec, par) {
    .Call(`_fable_tbats_tbats_pack_parameters`, spec, par)
}

tbats_unpack_parameters <- function(spec, vector) {
    .Call(`_fable_tbats_tbats_unpack_parameters`, spec, vector)
}

tbats_parameter_scales <- function(spec) {
    .Call(`_fable_tbats_tbats_parameter_scales`, spec)
}

tbats_filter <- function(spec, par, y, x0) {
    .Call(`_fable_tbats_tbats_filter`, spec, par, y, x0)
}

tbats_forecast_model_scale <- function(spec, par, x_last, sigma2, h) {
    .Call(`_fable_tbats_tbats_forecast_model_scale`, spec, par, x_last, sigma2, h)
}

tbats_simulate_model_scale <- function(spec, par, x_last, innovations) {
    .Call(`_fable_tbats_tbats_simulate_model_scale`, spec, par, x_last, innovations)
}

tbats_box_cox <- function(y, lambda) {
    .Call(`_fable_tbats_tbats_box_cox`, y, lambda)
}

tbats_inv_box_cox <- function(z, lambda, variance) {
    .Call(`_fable_tbats_tbats_inv_box_cox`, z, lambda, variance)
}

tbats_guerrero_lambda <- function(y, period, lower, upper) {
    .Call(`_fable_tbats_tbats_guerrero_lambda`, y, period, lower, upper)
}

tbats_seed_states <- function(spec, par, y) {
    .Call(`_fable_tbats_tbats_seed_states`, spec, par, y)
}

tbats_neg2loglik <- function(spec_list, par_list, y, seed) {
    .Call(`_fable_tbats_tbats_neg2loglik`, spec_list, par_list, y, seed)
}

tbats_fit_specific <- function(spec, y, init_lambda, optimizer, bias_adjust) {
    .Call(`_fable_tbats_tbats_fit_specific`, spec, y, init_lambda, optimizer, bias_adjust)
}

tbats_arma_loglik <- function(y, ar, ma, mean) {
    .Call(`_fable_tbats_tbats_arma_loglik`, y, ar, ma, mean)
}

tbats_arma_fit <- function(y, p, q, optimizer) {
    .Call(`_fable_tbats_tbats_arma_fit`, y, p, q, optimizer)
}

tbats_arma_select <- function(y, max_p, max_q, optimizer) {
    .Call(`_fable_tbats_tbats_arma_select`, y, max_p, max_q, optimizer)
}

